#!/bin/bash

set -e

if ! [ $(id -u) = 0 ]; then
   echo "The script need to be run as root." >&2
   exit 1
fi

if [ $SUDO_USER ]; then
    real_user=$SUDO_USER
else
    real_user=$(whoami)
fi


ARCH="x86_64"
VERSION="2019.09.01"
IMAGE="archlinux-bootstrap-$VERSION-$ARCH.tar.gz"
MIRROR="http://mirror.rackspace.com/archlinux/iso/$VERSION/$IMAGE"

FAKEROOT="https://aur.archlinux.org/cgit/aur.git/snapshot/fakeroot-tcp.tar.gz"
DAEMONIZE="https://aur.archlinux.org/cgit/aur.git/snapshot/daemonize.tar.gz"

HOSTESS="https://github.com/cbednarski/hostess/releases/download/v0.3.0/hostess_linux_amd64"
GENIE="https://github.com/arkane-systems/genie/releases/download/1.12/genie.tar.gz"

# Get the current directory
BUILDDIR=$(cd `dirname $0` && pwd -P)

# ! Fakeroot-tcp no longer necessary with WSL2
# Prepare fakeroot-tcp as the normal (non-root) user
# sudo -u $real_user sh <<EOF
# set -e

# # Get somewhere in tmp to work (as non-root)
# cd \$(mktemp -d)

# # Note you'll need the dependencies for this...
# curl -LO "${FAKEROOT}"
# tar xzf "fakeroot-tcp.tar.gz"
# cd fakeroot-tcp
# makepkg
# cp "\$(pwd)/\$(ls | grep pkg.)" "$BUILDDIR/fakeroot.pkg.gz"
# EOF

# Prepare daemonize as the normal (non-root) user
sudo -u $real_user sh <<EOF
set -e

# Get somewhere in tmp to work (as non-root)
WORKDIR=\$(mktemp -d)
cd \$WORKDIR

# Note you'll need the dependencies for this...
curl -LO "$DAEMONIZE"
tar xzf "daemonize.tar.gz"
cd daemonize
makepkg
cp "\$(pwd)/\$(ls | grep pkg.)" "$BUILDDIR/daemonize.pkg.gz"
rm -rf \$WORKIR
EOF

# Get a new working directory (as root)
WORKDIR=$(mktemp -d)
cd $WORKDIR

# Get the base image
curl -LO $MIRROR
tar xzf $IMAGE

# Stop us breaking things!
mount --bind root.$ARCH root.$ARCH
cd root.$ARCH

# Set up internet and pacman configs...
cp -r $BUILDDIR/linux_files/etc/* etc/
sed -i -e 's/#en_US.UTF-8/en_US.UTF-8/' etc/locale.gen
echo "LANG=en_US.UTF-8" > etc/locale.conf
echo "LANGUAGE=en_US.UTF-8" >> etc/locale.conf
echo "LC_ALL=en_US.UTF-8" >> etc/locale.conf

# ! Fakeroot-tcp no longer necessary with WSL2
# Copy over the fakeroot package
# cp "$BUILDDIR/fakeroot.pkg.gz" root/

# Copy over the daemonize package
cp "$BUILDDIR/daemonize.pkg.gz" root/

# ...Initialise pacman
arch-chroot . pacman-key --init
arch-chroot . pacman-key --populate archlinux

# Fix localization
arch-chroot . pacman -Sy --noconfirm sed gzip
arch-chroot . locale-gen

# Update the install, and add stuff!
arch-chroot . pacman -Syu --noconfirm
arch-chroot . pacman -S --noconfirm base base-devel sudo ccache clang pigz pbzip2 git

# Now remove and disable the linux kernel install
arch-chroot . pacman -Rsc --noconfirm linux-firmware
sed -i -e 's/#IgnorePkg   =/IgnorePkg   =/' etc/pacman.conf
rm etc/pacman.d/hooks/90-linux.hook

# ! Fakeroot-tcp no longer necessary with WSL2
# yes | arch-chroot . pacman -U /root/fakeroot.pkg.gz

# We need Genie for systemd support...
# ...Install its dependencies
arch-chroot . pacman -S --noconfirm polkit dotnet-runtime
yes | arch-chroot . pacman -U /root/daemonize.pkg.gz

curl -Lo usr/bin/hostess $HOSTESS
arch-chroot . chmod a+rx /usr/bin/hostess

# ...And install it
cd root/
mkdir genie && cd genie
curl -LO $GENIE
tar xzf `basename $GENIE`
rm `basename $GENIE`
cp systemd-genie/usr/bin/* ../../usr/local/bin
cd ../../

# ...Set the permissions
arch-chroot . chmod u+s /usr/local/bin/genie
arch-chroot . chmod a+rx /usr/local/bin/genie

# ...Genie recommendations
arch-chroot . systemctl disable getty@tty1

# And make the final touches!
rm etc/resolv.conf
cat > etc/resolv.conf << EOF
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
EOF
sed -i -e "s/^# %wheel ALL=.*NOPASSWD:.*$/%wheel ALL=(ALL) NOPASSWD: ALL/" etc/sudoers

# Copy in user overrides
[ -d "$BUILDDIR/linux_overrides/etc/" ] && cp -r $BUILDDIR/linux_overrides/etc/* etc/

# Run the user-overrides script if it exists...
if [ -f "$BUILDDIR/linux_overrides/runme.sh" ]; then
    cp -r $BUILDDIR/linux_overrides/runme.sh root/
    chmod +x root/runme.sh
    arch-chroot . /root/runme.sh
fi

# Finish install
yes | arch-chroot . pacman -Scc

# Now to tidy up...
umount -l .
/bin/rm -rf tmp/*
/bin/rm -rf root/*
/bin/rm -rf var/cache/pacman/pkg/*

# tar the rootfs, and drop it in the build directory
tar --ignore-failed-read -czf $BUILDDIR/install.tar.gz *
chown $real_user:$real_user $BUILDDIR/install.tar.gz

# delete the working directory
rm -rf $WORKDIR
